### ISSUE TITLE
Out of norm project

### ISSUE THREAD

**Issue by fde-capu** [appinha/ip_calc-netwhat-42cursus#1]
Hello, I find it very sweet you have developed your own IP calculator, congrats!
Since it has the 42 header, should not you follow the Norminette specifications?
It would make your code much prettier.
Cheers!

**Comment by appinha** [comment]
Hi, I think your attempt to give people feedback on their code really cute!
Unfortunately “a pretty code” has nothing to do with following the Norm, nor does using a 42 header. Some valid arguments would be “to improve readability” or “since it’s a C language, 42 project from the inner circle”.
I’m sure you’ll get there next time ☺️
Cheers!
